# Generated by Django 3.0.13 on 2021-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cab", "0003_auto_20200803_1425"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="version",
            field=models.CharField(
                choices=[
                    ("3.0", "3.0"),
                    ("2.2", "2.2"),
                    ("2.1", "2.1"),
                    ("2.0", "2.0"),
                    ("1.11", "1.11"),
                    ("1.10", "1.10"),
                    ("1.9", "1.9"),
                    ("1.8", "1.8"),
                    ("1.7", "1.7"),
                    ("1.6", "1.6"),
                    ("1.5", "1.5"),
                    ("1.4", "1.4"),
                    ("1.3", "1.3"),
                    ("1.2", "1.2"),
                    ("1.1", "1.1"),
                    ("1.0", "1.0"),
                    ("0.96", ".96"),
                    ("0.95", "Pre .96"),
                    ("0", "Not specified"),
                ],
                default="0.0",
                max_length=5,
            ),
        ),
    ]
