# Generated by Django 3.2rc1 on 2021-04-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0004_auto_20210310_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
