# Generated by Django 4.2.23 on 2025-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cab", "0005_alter_snippet_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="version",
            field=models.CharField(
                choices=[
                    ("5.2", "5.2"),
                    ("5.1", "5.1"),
                    ("5.0", "5.0"),
                    ("4.2", "4.2"),
                    ("4.1", "4.1"),
                    ("4.0", "4.0"),
                    ("3.2", "3.2"),
                    ("3.1", "3.1"),
                    ("3.0", "3.0"),
                    ("2.2", "2.2"),
                    ("2.1", "2.1"),
                    ("2.0", "2.0"),
                    ("1.11", "1.11"),
                    ("1.10", "1.10"),
                    ("1.9", "1.9"),
                    ("1.8", "1.8"),
                    ("1.7", "1.7"),
                    ("1.6", "1.6"),
                    ("1.5", "1.5"),
                    ("1.4", "1.4"),
                    ("1.3", "1.3"),
                    ("1.2", "1.2"),
                    ("1.1", "1.1"),
                    ("1.0", "1.0"),
                    ("0.96", ".96"),
                    ("0.95", "Pre .96"),
                    ("0", "Not specified"),
                ],
                default="0.0",
                max_length=5,
            ),
        ),
    ]
